django1/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "django1"

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path('elementaryCellularAutomata/', include('elementaryCellularAutomata.urls')),
    path('pasteAsMarkdown/', include('pasteAsMarkdown.urls')),
    path('hashid/', include('hashid.urls'))
]

elementaryCellularAutomata/urls.py
from django.urls import path

from . import views

app_name = "elementaryCellularAutomata"

urlpatterns = [
    path('form/', views.WolfForm.as_view(), name='form'),
    path('show/', views.show, name='show'),
]

hashid/urls.py
from django.urls import path

from . import views

app_name = "hashid"

urlpatterns = [
    path('form/', views.HashForm.as_view(), name='form'),
    path('show/', views.show, name='show'),
]

pasteAsMarkdown/urls.py
from django.urls import path

from . import views

app_name = "pasteAsMarkdown"

urlpatterns = [
    path('form/', views.PasteFormMarkdown.as_view() , name='form'),
    path('create/', views.create_url, name="create"),
    path('show/<str:path>', views.show, name='show'),
]

hashid/models.py
from django.db import models

# Create your models here.

pasteAsMarkdown/models.py
from django.db import models


class MarkdownModel(models.Model):
    markdown_txt = models.TextField()
    path = models.CharField(blank=True, unique=True, max_length=40)

    def __str__(self):
        return self.markdown_txt

elementaryCellularAutomata/forms.py
from django import forms


class WolframForm(forms.Form):
    nmb = forms.IntegerField(min_value=0, max_value=256)

hashid/forms.py
from django import forms


class HashidForm(forms.Form):
    hash_value = forms.CharField(required=True)

django1/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'django1/index.html')

elementaryCellularAutomata/views.py
from django.http import HttpResponse
from django.views import generic
from elementaryCellularAutomata.forms import WolframForm
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
import matplotlib.pyplot as plt
import numpy as np


def Wolf(x):
    buffer = []
    rule = int(x)
    rules = list(f"{rule:08b}")
    rules = [ int(x) for x in rules ]
    A = np.zeros((40, 79), dtype = int)

    A[0, 39] = 1

    def executeRules(a, b, c):
        if a == 1 and b == 1 and c == 1:
            return rules[0]
        if a == 1 and b == 1 and c == 0:
            return rules[1]
        if a == 1 and b == 0 and c == 1:
            return rules[2]
        if a == 1 and b == 0 and c == 0:
            return rules[3]
        if a == 0 and b == 1 and c == 1:
            return rules[4]
        if a == 0 and b == 1 and c == 0:
            return rules[5]
        if a == 0 and b == 0 and c == 1:
            return rules[6]
        if a == 0 and b == 0 and c == 0:
            return rules[7]
        return 0

    for i, row in enumerate(A):
        if(i != 0):
            for j in range(len(A[i])):
                if j is 0:
                    a = 0
                else:
                    a = A[i-1, j-1]

                b = A[i-1, j]

                if j is len(row) - 1:
                    c = 0
                else:
                    c = A[i-1, j+1]
                A[i, j] = executeRules(a, b, c)
        line = ""
        for _, letter in enumerate(A[i]):
            if int(letter) is 0:
                line = line + "."
            else:
                line = line + "#"
        buffer.append(line)
    return '\n'.join(buffer)

def show(request):
    nmb = int(request.POST['nmb'])
    if not 0 <= nmb <= 256:
        raise ValidationError("parameter rule number should have a value between 0 and 256")
    
    value = Wolf(nmb)
    return render(request, 'elementaryCellularAutomata/show.html', {
        'string': value,
        'nmb': nmb,
    })


class WolfForm(FormView):
    template_name = 'elementaryCellularAutomata/form.html'
    form_class = WolframForm
    success_url = reverse_lazy('show')

hashid/views.py
from django.http import HttpResponse
from django.views import generic
from hashid.forms import HashidForm
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
import re
import argparse

list_hash = {}

list_hash["md5"] = '^[a-f0-9]{32}(:.+)?$'
list_hash["sha1"] = '^[a-f0-9]{40}(:.+)?$'
list_hash["sha224"] = '^[a-f0-9]{56}$'
list_hash["Blowfish(bcrypt)"] = '^(\$2[axy]|\$2)\$[0-9]{2}\$[a-z0-9\/.]{53}$'
list_hash["drupal7"] = '^\$S\$[a-z0-9\/.]{52}$'
list_hash["Cisco-PIX"] = '^[a-z0-9\/.]{16}$'
list_hash["Wordpress v2.6.0/2.6.1"] = '^\$H\$[a-z0-9\/.]{31}$'
list_hash["MySQL5.x"] = '^\*[a-f0-9]{40}$'
list_hash["Minecraft(AuthMe Reloaded)"] = '^\$sha\$[a-z0-9]{1,16}\$([a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64}|[a-f0-9]{128}|[a-f0-9]{140})$'
list_hash["PostgreSQL"] = '^md5[a-f0-9]{32}$'
list_hash["Microsoft Office 2013"] = '^\$office\$\*2013\*[0-9]{6}\*[0-9]{3}\*[0-9]{2}\*[a-z0-9]{32}\*[a-z0-9]{32}\*[a-z0-9]{64}$'
list_hash["IPMI2 RAKP HMAC-SHA1"] = '^[a-f0-9]{130}(:[a-f0-9]{40})?$'


def find_hash(string):    
    for hash_name, regex in list_hash.items():
            if re.compile(regex, re.IGNORECASE).match(string) is not None:
                    return hash_name




def show(request):
    hash_value = request.POST['hash_value']
    
    value = find_hash(hash_value)

    return render(request, 'hashid/show.html', {
        'string': value,
        'hash_value': hash_value,
    })


class HashForm(FormView):
    template_name = 'hashid/form.html'
    form_class = HashidForm
    success_url = reverse_lazy('show')

pasteAsMarkdown/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.forms import ModelForm
from django.urls import reverse_lazy
from pasteAsMarkdown.models import MarkdownModel
from markdown2 import Markdown
from django.views.generic.edit import FormView
import uuid



class PastebinForm(ModelForm):
    class Meta:
        model = MarkdownModel
        fields = ["markdown_txt", "path"]



class PasteFormMarkdown(FormView):
    template_name = 'pasteAsMarkdown/form.html'
    form_class = PastebinForm



def create_url(request):
    if request.POST['markdown_txt']:
        if not request.POST['path']:
            path = str(uuid.uuid4())
        else:
            path = request.POST['path']
        a = MarkdownModel(markdown_txt=request.POST['markdown_txt'], path=path)
        a.save()
        # print(Markdown.objects.all())
        return HttpResponseRedirect(f"/pasteAsMarkdown/show/{a.path}")

def show(request, path):
    markdowner = Markdown()
    markdown_txt = markdowner.convert(str(MarkdownModel.objects.get(path=path)))
    return render(request, 'pasteAsMarkdown/show.html', {
        'path' : path,
        'markdown_txt' : markdown_txt
    })

django1/templates/django1/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h1>Welcome to the django1 project</h1>
        <p>Check the navbar to navigate between each differents applications ! Have fun (:</p>
    </div>
</body>

</html>

elementaryCellularAutomata/templates/elementaryCellularAutomata/form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <form action="{% url 'elementaryCellularAutomata:show'%}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</body>

</html>

elementaryCellularAutomata/templates/elementaryCellularAutomata/show.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h1>For rule {{ nmb }}, we have : </h1>

        <div>
            <pre>{{ string|linebreaks }}</pre>
        </div>
    </div>
</body>

</html>

hashid/templates/hashid/form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <form action="{% url 'hashid:show'%}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</body>

</html>

hashid/templates/hashid/show.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h3>For the string hash '{{ hash_value }}' : </h3>
        <div>
            <p>{% if string == None %} Hash not found :( {% else %} Hash found : {{ string }} {% endif %}</p>
        </div>
    </div>
</body>

</html>

pasteAsMarkdown/templates/pasteAsMarkdown/form.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <form action="{% url 'pasteAsMarkdown:create'%}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</body>

</html>

pasteAsMarkdown/templates/pasteAsMarkdown/show.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">Django1</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'elementaryCellularAutomata:form'%}">Elementary Cellular Automata</a></li>
                <li><a href="{% url 'hashid:form' %}">Hashid</a></li>
                <li><a href="{% url 'pasteAsMarkdown:form' %}">Paste As Markdown</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h3>In this url : {{path}} </h3>
        <div>
            {{markdown_txt|safe }}
        </div>
    </div>
</body>

</html>